//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_barcode
    {
        public int BARKOD { get; set; }
        public Nullable<int> URUN { get; set; }
        public string YORUM { get; set; }
        public Nullable<int> EKLEYEN_KULLANICI { get; set; }
        public Nullable<decimal> fiyati { get; set; }
    }
}
