//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_cargo_company
    {
        public int SIRA_NO { get; set; }
        public string KOD { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<bool> ALICI_ODER { get; set; }
        public string ODEME_PLANI { get; set; }
        public string CARI_KODU { get; set; }
        public string KARGO_ADI { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
