//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_discountcart
    {
        public int SIRA_NO { get; set; }
        public string KOD { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string ŞEKLİ { get; set; }
        public string BIRIM { get; set; }
        public Nullable<int> DEGER { get; set; }
        public Nullable<int> FORMUL { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
