//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_e_waybill
    {
        public int SIRA_NO { get; set; }
        public string SUBE { get; set; }
        public string DEPO { get; set; }
        public string MAKBUZ_NO { get; set; }
        public string DOKUMAN_NO { get; set; }
        public string IRSALIYE_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string PARA_BIRIMI { get; set; }
        public string CARI { get; set; }
        public string TESLIMAT_ADRESI { get; set; }
        public string ACIKLAMA { get; set; }
        public string BARKOD { get; set; }
        public string ARAC { get; set; }
        public string KARGO_SIRKETI { get; set; }
        public Nullable<System.DateTime> kARGO_GONDERIM_TARIHI { get; set; }
        public Nullable<decimal> ARA_TOPLAM { get; set; }
        public Nullable<decimal> MALIYET { get; set; }
        public Nullable<decimal> INDIRIM { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> GENEL_TOPLAM { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
