//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_employee_permission
    {
        public int SIRA_NO { get; set; }
        public string CALISAN { get; set; }
        public Nullable<System.DateTime> IZIN_TARIHI { get; set; }
        public string IZIN_NEDENI { get; set; }
    }
}
