//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_imports_export
    {
        public int SIRA_NO { get; set; }
        public string TIP { get; set; }
        public string KOD { get; set; }
        public string CARI { get; set; }
        public string SEHIR { get; set; }
        public string ILCE { get; set; }
        public string ULKE { get; set; }
        public string METHOD { get; set; }
        public string DOKUMAN_NO { get; set; }
        public string PARA_BIRIMI { get; set; }
        public string TASIMA_TIPI { get; set; }
        public string KARGO_NO { get; set; }
        public string BANKA { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
