//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_payment_plan
    {
        public int SIRA_NO { get; set; }
        public Nullable<int> KOD { get; set; }
        public Nullable<int> INDIRIM { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
