//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_product
    {
        public int NO { get; set; }
        public string MARKA { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string TIPI { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
