//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_product_type
    {
        public int SIRA_NO { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> KAYIT_TARIHI { get; set; }
        public string EKLEYEN_KULLANICI { get; set; }
    }
}
