//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_product_refund
    {
        public int SIRA_NO { get; set; }
        public string IADE_NEDENI { get; set; }
        public Nullable<int> IADE_MIKTARI { get; set; }
        public string ARAC { get; set; }
        public string URUN { get; set; }
        public Nullable<System.DateTime> IADE_TARIHI { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
