//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_repository
    {
        public int SIRA_NO { get; set; }
        public string DEPO_ADI { get; set; }
        public string SEHIR { get; set; }
        public string ILCE { get; set; }
        public string ULKE { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
