//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_shipment_slip
    {
        public int SIRA_NO { get; set; }
        public string TIPI { get; set; }
        public string FIS_NO { get; set; }
        public Nullable<System.DateTime> FIS_TARIHI { get; set; }
        public string ODEME_PLANI { get; set; }
        public string CARGO_SIRKETI { get; set; }
        public string TESLIM { get; set; }
        public string ACIKLAMA { get; set; }
        public string PAKETLEME { get; set; }
        public string ALICI_CARI { get; set; }
        public string GONDEREN_CARI { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<System.DateTime> KARGO_TESLIM_TARIHI { get; set; }
        public string KARGO_FATURA_NO { get; set; }
        public Nullable<decimal> TOPLAM_TUTAR { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
