//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_sold_product
    {
        public int SIRA_NO { get; set; }
        public string DOKUMAN_NO { get; set; }
        public string SATILAN_URUN { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string BIRIM { get; set; }
        public string ARAC { get; set; }
        public string ODEME_PLANI { get; set; }
        public Nullable<decimal> MALIYET { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
