//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_suppliers
    {
        public int SIRA_NO { get; set; }
        public string CARI_TIPI { get; set; }
        public string CARI_KOD { get; set; }
        public string UNVAN { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string ACIKLAMA { get; set; }
        public string VERGI_DAIRESI { get; set; }
        public string VERGI_KODU { get; set; }
        public string E_MAIL { get; set; }
        public string E_FATURA_TIPI { get; set; }
        public string ADRES { get; set; }
        public string POSTA_KODU { get; set; }
        public string SEHIR { get; set; }
        public string ILCE { get; set; }
        public string ULKE { get; set; }
        public string CEP_TELEFON { get; set; }
        public string TELEFON_1 { get; set; }
        public string TELEFON_2 { get; set; }
        public string FAX { get; set; }
        public string SEKTOR { get; set; }
        public string INDIRIM_PLANI { get; set; }
        public string EKLEYEN_KULLANICI { get; set; }
        public Nullable<System.DateTime> EKLEME_TARIHI { get; set; }
    }
}
