//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Users
    {
        public int SIRA_NO { get; set; }
        public string KULLANICI_ADI { get; set; }
        public string CALISAN { get; set; }
        public string SIFRE { get; set; }
        public string YETKI { get; set; }
        public string SIRKET { get; set; }
        public Nullable<System.DateTime> KAYIT_TARIHI { get; set; }
    }
}
