//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHBYS.ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_vehicle
    {
        public int SIRA_NO { get; set; }
        public string ARAC_TIPI { get; set; }
        public string KOD { get; set; }
        public string CALISAN { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string PLAKA { get; set; }
        public Nullable<int> BENZIN_DEPOSU { get; set; }
        public Nullable<System.DateTime> ARACIN_SON_BAKIM_TARIHI { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
